config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    get 'about', to: 'pages#about'
    get 'what', to: 'pages#what'
    get 'learn1', to: 'pages#learn1'
    get 'learn2', to: 'pages#learn2'
    get 'learn3', to: 'pages#learn3'
    get 'learn4', to: 'pages#learn4'
    get 'learn5', to: 'pages#learn5'
    get 'learn6', to: 'pages#learn6'
    resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
  end
  
end

app/controllers/pages_controller.rb
class PagesController <ApplicationController
    def home
    end
    
    def about
    end
    
    def what
    end
    
    def learn1
    end
    
    def learn2
    end
    
    def learn3
    end
    
    def learn4
    end

    def learn5
    end
    
    def learn6
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
      <h3 class="text-center">A Bitcoin for your thoughts</h3>
      
      <div class="col-md-4 col-md-offset-4"
       
      
      <%= form_for "/contacts" do |f| %>
      
      <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
      </div>
        
      <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>
      </div>
        
      <div class="form-group">
        <%= f.label :comments %>
        <%= f.text_area :comments, class: 'form-control' %>
      </div>
      
      
        <%= f.submit 'Submit', class: 'btn btn-default' %>
        <% end %>
   
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <%= link_to root_path , class: "navbar-brand" do %>
          <i class="fa fa-cubes"></i>
          Mr Computer
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Who am I", about_path %></li>
            <li><%= link_to "What I learned", what_path %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div>
    </nav>
    
    
    <%= yield %>
  
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">

<body>

<div class="container-fluid bg-1 text-center text-no-navbar">
  <img src="http://www.iskin.co.uk/wallpapers/styles/2048x2048/public/electronic_circuit.jpg" class="img-circle img-responive" 
  id="MrComputer">
  </br>
  </br>
  </br>
  </br>
    <h5>I'm a visual representation on how my makers chooses to waste her free time</h5>
</div>
<div class="container-fluid bg-2 text-center">
    <h5>I am a workplace and a notebook at the same time.</h5>
</div>
<div class="container-fluid bg-1 text-right">
    <h3><strong>Medicine is not beautiful!</strong></h3>
</div>
<footer class="container-fluid bg-1 text-center">
  <p>Bootstrap Theme Made By <a href="http://www.w3schools.com">www.w3schools.com</a></p> 
</footer>
</body>
</html>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <h1>Welcome to the artificial mind</h1>
  <h3>I'm pleased to meet you</h3>
</div>

app/views/pages/learn1.html.erb
<div class ="text-center">
<h4>How to add a subpage</h4>
</div>
<div class ="text-left">
    <ul class="list-unlisted">
                <li class ="list-unlisted-item"> In linux: touch app/views/pages/newpagename.html.erb</li>
                <li class ="list-unlisted-item"> Make content of the New page</li>
                <li class ="list-unlisted-item"> In app/controllers/pages_controller.rb edit file accordingly</li>
                <li class ="list-unlisted-item"> In app/config/locales/routes.rb make changes accordingly</li>
                <li class ="list-unlisted-item"> In a leading website make your site a link in an list in .navbar or otherwise</li>
                <li class ="list-unlisted-item"> Congrats, clever girl!</li>
    </ul>
    </div>

app/views/pages/learn2.html.erb
<div class ="text-center">
<h4>How to save stuff in github</h4>
</div>
<div class ="text-left">
    <ul class="list-unlisted">               
                <li class ="list-unlisted-item"> git status</li>
                <li class ="list-unlisted-item"> git add .</li>
                <li class ="list-unlisted-item"> git commit -m "title"</li>
                <li class ="list-unlisted-item"> git push origin pages_and_layouts</li>
                <li class ="list-unlisted-item"> Congrats, clever girl!</li>
    </ul>
  </div>

app/views/pages/learn3.html.erb
<!DOCTYPE html>

<body>
<table style="width:75%", class="table-condensed tabelka">
  <tr>
    <th>Tag</th>
    <th>Function</th> 
  </tr>
  <tr class="inbetween, col-md-2">
      <td colspan="2">Lists</td>
    </tr>
  <tr>
    <td>
        <p>&lt;ol&gt;</p>
        <p>&lt;li&gt; &lt;/li&gt;</p>
        <p>&lt;li&gt; &lt;/li&gt;</p>
        <p>&lt;/ol&gt; </p>
    </td>
    <td>Ordered list</td> 
  </tr>
   <tr>
    <td>
        <p>&lt;ul&gt;</p>
        <p>&lt;li&gt; &lt;/li&gt;</p>
        <p>&lt;li&gt; &lt;/li&gt;</p>
        <p>&lt;/ul&gt; </p>
    </td>
    <td>Unordered list</td> 
  </tr>
   <tr class="inbetween">
    <td colspan="2">
        Links and images
    </td>
  </tr>
  <tr>
    <td>
        &lt;a href="link"&gt; &lt;/a&gt;
    </td>
    <td>Adding a clickable link</td>
  </tr>
  <tr>
    <td>
        &lt;img src="link"&gt; &lt;/img&gt;
    </td>
    <td>Adding an image</td>
  </tr>
   <tr>
    <td>
        &lt;a href="link"&gt;&lt;img src="link"&gt&lt;/img&gt;&lt;/a&gt;
    </td>
    <td>Adding an image link</td>
  </tr>
  <tr>
    <td>
        &lt;element class="class1 class2"&gt;&lt;/element&gt;
    </td>
    <td>Adding double CSS classes to an element</td>
  </tr>
  <tr>
    <td>
        &lt;!-- comment --&gt;
    </td>
    <td>HTML comment</td>
  </tr>
   <tr class="inbetween">
    <td colspan="2">
        HTML styling
    </td>
    </tr>
    <tr>
    <td>
        &lt;p style="font-size: Xpx"&gt;&lt;/p&gt;
    </td>
    <td>Font size (in px)</td>
  </tr>
  <tr>
    <td>
        &lt;p style="color: red"&gt;&lt;/p&gt;
    </td>
    <td>Changing colors, <a href="https://www.w3.org/TR/css3-color/#svg-color">available list of color keywords</a></td>
  </tr>
  <tr>
    <td>
        &lt;p style="color: red; font-size: 40px"&gt;&lt;/p&gt;
    </td>
    <td>Adding double style atribute in HTML</td>
  </tr>
   <tr>
    <td>
        &lt;p style="font-family: Arial"&gt;&lt;/p&gt;
    </td>
    <td>Changing font style, <a href="https://www.w3.org/TR/CSS21/fonts.html#generic-font-families">available list of fonts</a></td>
  </tr>
   <tr>
    <td>
        &lt;p style="backgroud-color: red"&gt;&lt;/p&gt;
    </td>
    <td>Changing backgroud color</td>
  </tr>
  </tr>
   <tr>
    <td>
        &lt;p style="text align: left/center/right"&gt;&lt;/p&gt;
    </td>
    <td>Text align</td>
  </tr>
   <tr>
    <td>
        &lt;strong&gt;text&lt;/strong&gt;
    </td>
    <td><strong>Bold</strong></td>
  </tr>
  <tr>
    <td>
        &lt;em&gt;text&lt;/em&gt;
    </td>
    <td><em>Italics</em></td>
  </tr>
  <tr>
      <td>&lt;/br&gt;</td>
      <td>Starting the new line (like with enter) - <em>no closing tag!</em></td>
  </tr>
  <tr>
      <td>& nbsp;</td>
      <td> non breaking space for tags</td>
  </tr>
  <tr class="inbetween">
     <td colspan= "2">Tables</td> 
  </tr>
    <tr>
    <td>
        &lt;table&gt;&lt;/table&gt;
    </td>
    <td>Table tag</td>
  </tr>
    <tr>
    <td>
        &lt;tr&gt;&lt;td&gt;data&lt;/td&gt;&lt;/tr&gt;
    </td>
    <td>New row, new data</td>
  </tr>
  <tr>
    <td>
        &lt;td colspan= "#of columns"&gt;data&lt;/td&gt;
    </td>
    <td>Row mending two columns</td>
  </tr>
   <tr>
    <td>
        &lt;tr&gt;
        &lt;th&gt;&lt;/th&gt;
        &lt;/th&gt;
    </td>
    <td>Table heading: sort of like td, but for headings</td>
  </tr>
  <tr class= "inbetween">
      <td colspan= "2">Division</td>
  </tr>
  <tr>
      <td>&lt;div style="width:50px; height:50px; other features like background color or so"&gt;&lt;/div&gt;</td>
      <td>Creating a div with certain dimensions and other features</td>
  </tr>
    <tr>
      <td>&lt;a href="link"&gt;&lt;div style="width:50px; height:50px; other features like background color or so"&gt;&lt;/div&gt;&lt;/a&gt;</td>
      <td>Making the div a link</td>
  </tr>
  <tr class="inbetween">
      <td colspan= "2">Span</td>
  </tr>
  <tr>
      <td> &lt;span style="..."&gt;&lt;/span&gt;</td>
      <td>use when applying styles to a smaller part that div, i.e. one world in a paragraph</td>
  </tr>
  <tr>
      <td> &lt;xmp&gt;&lt;/xmp&gt;</td>
      <td>Putting code contet into display</td>
  </tr>
  
</table>
</body>

app/views/pages/learn4.html.erb
<!DOCTYPE html>

<table style="width:75%", class="table-condensed tabelka">
    <tr>
        <th colspan= "2">Tag</th>
        <th>Function</th>
    </tr>
    <tr>
        <td class="inbetween" colspan= "3">General</td>
    </tr>
    <tr>
        <td colspan="2"> &lt;link type="text/css" rel="stylesheet" href="stylesheet.css"/&gt;</td>
        <td>The CSS introduction in .html file (in head)<span style="color: hotpink"> it's also a self closing tag!</span></td>
    </tr>
    <tr>
        <td colspan="2"><p>class &#123; color: blue;</p>
            <p>&#125;</p>
        </td>
        <td>Changing colors, #hex for hexadecimal value <a href="http://www.hexcolortool.com/">Hex color tool</a></td>
    </tr>
    <tr>
        <td colspan="2"><p>class &#123; font-family: cursive, some other, some other;</p>
            <p>&#125;</p>
        </td>
        <td>Changing font family, popular (most basic) options are serif, sans-serif and cursive
        - add other options after a coma for backup</td>
    </tr>
    <tr>
        <td colspan="2"> font-size: Xpx;</td>
        <td> Changing font size</td>
    </tr>
    <tr>
        <td colspan="2"> font-size: Xem;</td>
        <td> Em is like px, but relative for screen size and therefore better
        for mobile devices. Valus are 1em, 0.5em, 2em and so on</td>
    </tr>
    <tr>
        <td colspan="2">background-color: yellow;</td>
        <td>Editing the background color</td>
    </tr>
    <tr>
        <td colspan="2">/*Comment*/</td>
        <td>CSS comments</td>
    </tr>
     <tr>
        <td colspan="2">&lt;style&gt;&lt;/style&gt;</td>
        <td>Putting CSS in .html</td>
    </tr>
    <tr>
        <td colspan= "3"   class="inbetween">Background</td>
    </tr>
    <tr>
        <td colspan="2">background-color: value;</td>
        <td>Setting background color</td>
    <tr>
        <td colspan= "2">line-height: 70%;</td>
        <td>Changing distance between lines, standart in a browser is around 110-120%</td>
    </tr>
    </tr>
    <tr>
        <td colspan="2">height: valuepx;</td>
        <td>Setting height value</td>
    </tr>
    <tr>
        <td colspan="2">width: valuepx;</td>
        <td>Setting width value</td>
    </tr>
    <tr>
        <td  class="inbetween" colspan= "3">Border</td>
    </tr>
    <tr>
        <td colspan="2">border: 1px solid red;</td>
        <td>Border values</td>
    </tr>
    <tr style="inbetween">
        <td colspan= "3">Selectors</td>
    </tr>
    <tr>
        <td class="firstrow">
            &lt;body&gt;</br>
            &nbsp;&lt;div&gt;</br>
            &nbsp;&nbsp;&lt;div&gt;</br>
            &nbsp;&nbsp;&nbsp;&lt;h3&gt;&lt;/h3&gt;</br>
            &nbsp;&nbsp;&lt;/div&gt;</br>
            &lt;/div&gt;</br>
            &lt;/body&gt;</br>
        </td>
        <td class="firstrow">
            div div h3 &#123; <br> 
            </br>
            &nbsp;&nbsp;&nbsp;&nbsp;color: blue;</br>
            &#125;</td>
        <td> Selecting a tag nested in other tags</td>
    </tr>
    <tr>
        <td colspan= "2">*</td>
        <td>Selects <em>every</em> element on the page</td>
    </tr>
    <tr>
        <td class="firstrow">
            <p>&lt;body&gt;</br>
            &nbsp;&lt;div&gt;</br>
            &nbsp;&nbsp;<strong>&lt;h3&gt;&lt;/h3&gt;</strong></br>
            &nbsp;&nbsp;&nbsp;&lt;ul&gt;</br>
            &nbsp;&nbsp;&nbsp;&nbsp;&lt;li&gt;</br>
            &nbsp;&nbsp;&nbsp;&nbsp;&lt;h3&gt;&lt;/h3&gt;</br>
            &nbsp;&nbsp;&nbsp;&lt;/li&gt;</br>
            &nbsp;&nbsp;&lt;/ul&gt;</br>
            &nbsp;&lt;/div&gt;</br>
            &lt;/body&gt;</p>
            </td>
        <td class="firstrow">
            <p>div &gt; h3 &#123;</br>
            </br>
        &nbsp;&nbsp;&nbsp;&nbsp;font-weight: bold;</br>
            &#125;</p>
            </td>
        <td>Selecting not <em>every</em> every element nested inside a tag,</br> but noly these that are direct
        childer of the tag</td>
    </tr>
    <tr>
        <td class="firstrow">
            &lt;div&gt;</br>
            &nbsp;&lt;h1 class="newclass"&gt;&lt;/h1&gt;</br>
            &nbsp; &nbsp;&lt;ul&gt;</br>
            &nbsp;&nbsp;&nbsp;&lt;li&gt;</br>
            &nbsp;&nbsp;&nbsp;&nbsp;&lt;h3 class="newclass"&gt;&lt;/h3&gt;</br>
            &nbsp;&nbsp;&nbsp;&lt;/li&gt;</br>
            &nbsp;&nbsp;&lt;/ul&gt;</br>
            &nbsp;&lt;/div&gt;</br>
            </td>
        <td class="firstrow">.newclass &#123;</br>
        </br>
         &nbsp;&nbsp;&nbsp;font-weight: bold;</br>
        &#125;</td>
        <td>Attributing a class to html elements, same class can be used for different html element type!</td>
    </tr>
        <tr>
        <td class="firstrow">
            &lt;div&gt;</br>
            &nbsp;&lt;h1 id="newid"&gt;&lt;/h1&gt;</br>
            &nbsp;&nbsp;&lt;ul&gt;</br>
            &nbsp;&nbsp;&nbsp;&lt;li&gt;</br>
            &nbsp;&nbsp;&nbsp;&nbsp;&lt;h3&gt;&lt;/h3&gt; </br>
            &nbsp;&nbsp;&nbsp;&lt;/li&gt;</br>
            &nbsp;&nbsp;&lt;/ul&gt;</br>
            &lt;/div&gt;
            </td>
        <td class="firstrow">#newid &#123;</br>
        </br>
        &nbsp;&nbsp;&nbsp;font-weight: bold;</br>
        &#125;</td>
        <td>Attributing an id to a certain element (usually only one)</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">element:pseudoclass</br>
        i.e. a:hover<br>
        a:visited</br>
        a:link
        </td>
        <td>Pseudoclasses added after selectors determine CSS for different states - i.e. hover, visited link etc.</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">&:pseudoclass</td>
        <td>nesting psudoclasses in CSS (with two {{}})</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">element:first-child</td>
        <td>Peudoclass selecting only specific pointed element types, that are also first children of their parent tag </td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">element:nth-child(n)</td>
        <td>Peudoclass selecting only specific pointed element types, that are also nth children of their parent tag </td>
    </tr>
    <tr>
        <td class="inbetween" colspan= "3">Positioning</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">display:block</br>display:inline-block</br>display:inline</br>dsiplay:none</td>
        <td>Display values for positioning: The inline-block value allows you to put <br>several block elements on the same line. The inline value places all your elements next to one </br>another, but not as blocks: they don't keep their dimensions.</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">margin: auto;</td>
        <td>Automatic margin is centered from left to right</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">margin-top: Xpx;</br>margin-left: Xpx;</br>margin-bottom: Xpx;</br>margin-right: Xpx;</br>
        margin: Xpx Xpx Xpx Xpx</td>
        <td>Defying margin - in the 2nd method goes in the order top-right-bottom-left (clockwise)</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">padding: Xpx;</br>
        padding: Xpx Xpx Xpx Xpx;</br>padding-right: Xpx;</br>padding-top: Xpx;</br>padding-bottom: Xpx;</br>padding-left: Xpx;</td>
        <td>Values of padding, when one vaulue is set it's even on eah side</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">positive value</td>
        <td>Moves content a certain number of pixels from the <em>right</em> screen border &#x2192;<strong>moves to the right or down</strong></td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">negative value</td>
        <td>Moves content a certain number of pixels from the <em>left</em> screen border &#x2192;<strong>moves to the left or up</strong></td>
    </tr>
    <tr>
        <td class="firstrow" colspan="2">float: right;</br>float: left;</br>float: top;</br>float: bottom;</td>
        <td>Tells the element to stick to one side of the screen</td>
    </tr>
    <tr>
        <td class="firstrow" colspan="2">clear: right;</br>clear: left;</br>clear: both</td>
        <td>Tells the element to clear the way for all lements occupying the right, the left or both</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">position: absolute;</br>position: static;</td>
        <td>When an element is static, it is positioned where normally such element should be placed. </br>
        When it's absolute its margins and stuff are positioned to the nearest <strong>also absolute</strong></br>
        element. Everything moves in position to other elements, not in position to the static background.</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">position: relative;</td>
        <td>Positions element not in position to the nearest element but in position to otherwise it would land</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">position: relative;</td>
        <td>Positions element not in position to the nearest element but in position to otherwise it would land</td>
    </tr>
    <tr>
        <td class="firstrow" colspan= "2">position: fixed;</td>
        <td>Positions element not in position to the nearest element but makes it glued to the screen (moves when scrolling)</td>
    </tr>
      <tr>
        <td class="firstrow" colspan= "2">z-index: 1;</td>
        <td>Determines stacking order, the highest the number, the more the element is on top - <strong>work only on positioned elements</strong></td>
    </tr>
        
</table>

app/views/pages/learn5.html.erb
<div class ="text-center">
<h4>How to add bootstrap</h4>
</div>
<div class ="text-left"> 
    <ul class="list-unlisted">
                <li class ="list-unlisted-item"> ###config/routes.rb: <xmp>root 'posts#index'</xmp></li>
                <li class ="list-unlisted-item"> ###app/views/layouts/page.html.erb (in head):
                
                <p><xmp><link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
                </xmp></p>
    </ul>
</div>

app/views/pages/what.html.erb
   <div class="list-group">
  <a href="https://rails-workspace-haszabaj.c9users.io/learn1" class="list-group-item">How to add a subpage</a>
 <a href="https://rails-workspace-haszabaj.c9users.io/learn2" class="list-group-item">How to save stuff in github</a>
    <a href="https://rails-workspace-haszabaj.c9users.io/learn3" class="list-group-item">HTML tags</a>
    <a href="https://rails-workspace-haszabaj.c9users.io/learn4" class="list-group-item">CSS tags</a>
    <a href="https://rails-workspace-haszabaj.c9users.io/learn5" class="list-group-item">Adding bootstrap</a>
    <a href="https://rails-workspace-haszabaj.c9users.io/learn6" class="list-group-item">Ruby</a>
  </div>
    